export const mobiles = [
    {
        id: "m1",
        name: "Samsung A32",
        sim: "Single SIM (Nano-SIM) or Dual SIM (Nano-SIM, dual stand-by)",
        color: "blue violet white black",
        ram: 6,
        rom: 128,
        price: 47395,
        size: "6.4 inches",
        quantity: 198,
        image: "/assets/samsung/g_A32.jpg",
        weight: "184 g",
        resolution: "1080 x 2400 pixels",
        platform: "OS Android 11, One UI 3.1",
        camera: " Multi Quad",
        bluetooth: "Bluetooth 5.0, A2DP, LE",
        battery: "5000 mah",    
        brandID: "cat1"
    },
    {
        id: "m2",
        name: "Realme C21",
        sim: "Single SIM or Dual SIM",
        color: "blue black",
        ram: 3,
        rom: 32,
        price: 26999,
        size: "6.5 inches",
        quantity: 19,
        image: "/assets/realme/c21.jpg",
        weight: "",
        resolution: "",
        platform: "Helio G35 Powerful Processor",
        camera: "13MP AI Triple Camera",
        bluetooth: "",
        battery: "5000mAh Massive Battery",    
        brandID: "cat2"
    },
    {
        id: "m3",
        name: "Oppo A16e",
        sim: "Dual SIM",
        color: "blue black",
        ram: 4,
        rom: 64,
        price: 29999,
        size: "6.52 inches",
        quantity: 0,
        image: "/assets/oppo/A16e.jpg",
        weight: "",
        resolution: "",
        platform: "OS Andriod 11",
        camera: "5MP",
        bluetooth: "",
        battery: "4230mAh",    
        brandID: "cat3"
    },
    {
        id: "m4",
        name: "Vivo V23",
        sim: "Dual SIM",
        color: "blue black",
        ram: 16,
        rom: 256,
        price: 105999,
        size: "6.52 inches",
        quantity: 290,
        image: "/assets/vivo/v23.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "50MP AF Front",
        bluetooth: "",
        battery: "",    
        brandID: "cat7"
    },
    {
        id: "m5",
        name: "Nokia 105",
        sim: "dual SIM",
        color: "black",
        ram: 0,
        rom: 0,
        price: 5000,
        size: "",
        quantity: 132,
        image: "/assets/nokia/n_105.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "",
        bluetooth: "",
        battery: "",    
        brandID: "cat8"
    },
    {
        id: "m6",
        name: "Infinix Zero X Pro",
        sim: "",
        color: "",
        ram: 8,
        rom: 128,
        price: 47999,
        size: "6.67 inches",
        quantity: 54,
        image: "/assets/infinix/zeroZpro.jpg",
        weight: "",
        resolution: "",
        platform: "Helio G95 Processor",
        camera: "108MP OIS Moonshot",
        bluetooth: "",
        battery: "4500 mAh",    
        brandID: "cat5"
    },
    {
        id: "m7",
        name: "vivo V23e",
        sim: "dual sim",
        color: "black golden multi",
        ram: 12,
        rom: 256,
        price: 73999,
        size: "6.5 inches",
        quantity: 209,
        image: "/assets/vivo/vivo-v23e.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "50MP AF Front - 44W",
        bluetooth: "",
        battery: "",    
        brandID: "cat7"
    },
    {
        id: "m8",
        name: "ITEL A23 PRO",
        sim: "Dual Sim",
        color: "",
        ram: 1,
        rom: 8,
        price: 11999,
        size: "5 inches",
        quantity: 21,
        image: "/assets/itel/a23.jpg",
        weight: "",
        resolution: "480 x 854 Pixels",
        platform: "",
        camera: "2 MP",
        bluetooth: "",
        battery: "2000 - 2999 mAh",    
        brandID: "cat6"
    },
    {
        id: "m9",
        name: "Itel A49",
        sim: "dual sim",
        color: "black blue",
        ram: 2,
        rom: 32,
        price: 18499,
        size: "6.6 inches",
        quantity: 12,
        image: "/assets/itel/a49.jpg",
        weight: "",
        resolution: "",
        platform: "Android 11.0 ",
        camera: "4 MP",
        bluetooth: " (Li-ion Non removable), 4000 mAh",
        battery: "",    
        brandID: "cat6"
    },
    {
        id: "m10",
        name: "Oppo A 37",
        sim: "Dual Sim",
        color: "OS 3.0",
        ram: 0,
        rom: 0,
        price: 8499,
        size: "5 inches",
        quantity: 12,
        image: "/assets/oppo/A37.jpg",
        weight: "",
        resolution: "720 x 1280 pixels",
        platform: "OSAndroid OS, v5.1",
        camera: "",
        bluetooth: "",
        battery: "",    
        brandID: "cat3"
    },
    {
        id: "m11",
        name: "realme C11",
        sim: "2 SIM + 1 MicroSD",
        color: "gray blue",
        ram: 4,
        rom: 64,
        price: 26799,
        size: "6.5 Large Display",
        quantity: 176,
        image: "/assets/realme/c11.jpg",
        weight: "",
        resolution: "",
        platform: "Octa-core Processor",
        camera: "",
        bluetooth: "",
        battery: "5000mAh Massive Battery",    
        brandID: "cat2"
    },
    {
        id: "m12",
        name: "OPPO Reno 6 Pro",
        sim: "dual sim",
        color: "steller black, aurora",
        ram: 17,
        rom: 256,
        price: 116999,
        size: "6.5 inches",
        quantity: 81,
        image: "/assets/oppo/reno6.jpg",
        weight: "177 g",
        resolution: "2400 x 1080",
        platform: "OS 11",
        camera: "8MP Ultra Wide-angle ",
        bluetooth: "",
        battery: "",    
        brandID: "cat3"
    },
    {
        id: "m13",
        name: "Apple iPhone 13 Pro Max",
        sim: "Dual SIM",
        color: "blue",
        ram: 16,
        rom: 512,
        price: 382499,
        size: "6.7 inches",
        quantity: 133,
        image: "/assets/apple/i13-pro.jpg",
        weight: "",
        resolution: "",
        platform: "ios 15",
        camera: " 12 MP, f/1.5, 26mm (wide)",
        bluetooth: "",
        battery: "4352 mAh, non-removable",    
        brandID: "cat4"
    },
    {
        id: "m14",
        name: "Samsung Galaxy A33",
        sim: "dual sim",
        color: "black",
        ram: 8,
        rom: 128,
        price: 76999,
        size: "6.4 inches",
        quantity: 0,
        image: "/assets/samsung/a33.jpg",
        weight: "186 g",
        resolution: "",
        platform: "",
        camera: "48 MP",
        bluetooth: "",
        battery: "",    
        brandID: "cat1"
    },
    {
        id: "m15",
        name: "Apple IPhone 7",
        sim: "dual sim",
        color: "black",
        ram: 2,
        rom: 128,
        price: 44999,
        size: "4.7 inches",
        quantity: 61,
        image: "/assets/apple/i7.jpg",
        weight: "",
        resolution: "750 x 1334 pixels",
        platform: "iOS 10.0.1",
        camera: "12 MP",
        bluetooth: "",
        battery: "Li-Ion 1960 mAh, non-removable",    
        brandID: "cat4"
    },
    {
        id: "m16",
        name: "Itel A49 ",
        sim: "dual sim",
        color: "black blue",
        ram: 2,
        rom: 32,
        price: 18199,
        size: "6.6 Inch",
        quantity: 14,
        image: "/assets/itel/a4916.jpg",
        weight: "150 g",
        resolution: "720 x 1520 Pixels ",
        platform: "",
        camera: "8 MP",
        bluetooth: "",
        battery: "1200 mah",    
        brandID: "cat6"
    },
    {
        id: "m17",
        name: "Nokia G21",
        sim: "",
        color: "",
        ram: 4,
        rom: 64,
        price: 27499,
        size: "6.5 inch",
        quantity: 187,
        image: "/assets/nokia/g21.jpg",
        weight: "",
        resolution: "",
        platform: "Android 11",
        camera: "50 MP",
        bluetooth: "",
        battery: "5050mAh",    
        brandID: "cat8"
    },
    {
        id: "m18",
        name: "itel it2173",
        sim: "dual sim",
        color: "black",
        ram: 0,
        rom: 0,
        price: 2400,
        size: "1.8 inches",
        quantity: 14,
        image: "/assets/itel/it2173.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "",
        bluetooth: "",
        battery: "",    
        brandID: "cat6"
    },
    {
        id: "m19",
        name: "vivo V23e",
        sim: "dual sim",
        color: "blue",
        ram: 12,
        rom: 256,
        price: 73999,
        size: "5.5 inch",
        quantity: 143,
        image: "/assets/vivo/23-e.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "50MP AF Front",
        bluetooth: "",
        battery: "",    
        brandID: "cat7"
    },
    {
        id: "m20",
        name: "Realme C25s",
        sim: "dual sim",
        color: "water blue, water gray",
        ram: 4,
        rom: 128,
        price: 33499,
        size: "6.5 inch",
        quantity: 1,
        image: "/assets/realme/c25.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "Triple 48 MP",
        bluetooth: "",
        battery: " Li-Po 6000 mAh, non-removable",    
        brandID: "cat2"
    },
    {
        id: "m21",
        name: "Apple iPhone 13 Pro",
        sim: "Single SIM and ESIM",
        color: "",
        ram: 12,
        rom: 128,
        price: 299000,
        size: "6.1 inches",
        quantity: 0,
        image: "/assets/apple/i13-pro.jpg",
        weight: "",
        resolution: "",
        platform: "iOS 15",
        camera: "12 MP, f/1.5, 26mm (wide)",
        bluetooth: "",
        battery: "3095 mAh, non-removable",    
        brandID: "cat4"
    },
    {
        id: "m22",
        name: "Infinix HOT 12 Play",
        sim: "dual sim",
        color: "Black, Legend White, Origin Blue, Lucky Green",
        ram: 4,
        rom: 64,
        price: 29999,
        size: "6.82 inches",
        quantity: 145,
        image: "/assets/infinix/hot12.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "front 8 MP",
        bluetooth: "",
        battery: "6000 MAH",    
        brandID: "cat5"
    },
    {
        id: "m23",
        name: "Infinix NOTE 12",
        sim: "dual sim",
        color: "sunset golden, black",
        ram: 6,
        rom: 128,
        price: 41999,
        size: "6.7 inches",
        quantity: 133,
        image: "/assets/infinix/note12.jpg",
        weight: "",
        resolution: "",
        platform: "",
        camera: "50MP",
        bluetooth: "",
        battery: "5000 mAh Battery",    
        brandID: "cat5"
    },
    {
        id: "m24",
        name: "Samsung Galaxy A13",
        sim: "dual sim",
        color: "black blue white peach",
        ram: 4,
        rom: 128,
        price: 38999,
        size: "6.6 inches",
        quantity: 41,
        image: "/assets/samsung/a13.jpg",
        weight: "",
        resolution: "",
        platform: " Android 12",
        camera: "8 MP",
        bluetooth: "",
        battery: "5000 mah",    
        brandID: "cat1"
    }    
]
